---
title: "R Notebook"
output: html_notebook
---


Todo

- simple path to basic summary plots

x-axis
y-axis - list with readouts for 'lapply'
legend - in plot with colors
facet-wrap - one (long) variable (e.g CRISPR gRNAs)
facet-grid - two shorter variables (e.g. cell line, time)

- chose box-plot if X is categorical or line-plot if continuous



```{r libraries call, include=FALSE}
require(tidyverse)
require(patchwork)

```

Data analysis

```{r data import}

# Import of meta data and organization of folders and files

# user input of which file to load
# should be a complete annotated data file (raw and meta data)
in_file <- "Bin_metadata_complete"
in_dir <- "./data/"

# output files and directory can be chosen
# these are defaults
# if "My_Plots" exists already it will be overwritten
out_file <- "My_Plots"
out_dir <- "./plots/"

# check if out_dir exists; if not make it
if (dir.exists(out_dir)==FALSE) {dir.create(out_dir)}

# import data
suppressMessages(data <- read_csv(paste0(in_dir,in_file,".csv")))

# assign unique experiment ID
# should be included in every plot generated by the script to link output to script and data
Exp_ID <- unique(data$Experiment_ID)


```


```{r data autocleanup}

# remove spaces in column names
colnames(data) <- gsub(" ", "_", colnames(data))

# remove all NAs in numeric and non-numeric columns

num_cols <- unname((sapply(data, is.numeric)))
non_num_cols <- !num_cols

data[num_cols][is.na(data[num_cols])] <- 0
data[non_num_cols][is.na(data[non_num_cols])] <- ""

glimpse(data)

```
```{r manual cleanup}
# manual clean up

data <- data %>%
     # drop Cell_Line and Time_point columns
     select(-Cell.line, -Timepoint) %>% 
     # split time into Time_days and Time_unit
     separate(Time, into = c("Time_days", "Time_unit"), extra = "drop", remove = T) %>%
     # remove rows where drug_ID is NULL (untreated)
     filter(drug_ID!="NULL")

# convert columns into the right data type
# Time should be numeric
data$Time_days <- as.numeric(data$Time_days)
data$cytokine_conc <- as.numeric(data$cytokine_conc)
data$cytokine_conc[is.na(data$cytokine_conc)] <- -1

# sort by Time, drug concentration
data <- data %>%
     arrange(Time_days, cytokine_conc)


```




```{r basic plots}
# trying out different scales and different x/y combinations to explore data

d1 <- data

ggplot(data=d1, aes(Time_days, Cell_No, color = cytokine_conc, group = cytokine_conc, shape = Cell_Line, group = Cell_Line)) +
          geom_point() +
          stat_summary(fun = mean, geom = "point") +
          stat_summary(fun = mean, geom = "line") + 
          facet_wrap( ~ Cell_Line, ncol=3)
          
ggplot(data=d1, aes(x=Time_days, y=Cyto_W3 , color = Cell_Line, group = Cell_Line)) +
          xlim(0.1, 500) +
#          ylim(0, 1000) +      
#          scale_x_continuous(trans=scales::pseudo_log_trans(base = 2)) +
          scale_x_continuous(trans='log2') +
          geom_point() +
          stat_summary(fun = mean, geom = "point") +
          stat_summary(fun = mean, geom = "line") + 
          facet_grid(antibody_ID ~ cytokine_conc)

          
ggplot(data=d1, aes(x=Time_days, y=Cyto_W3 , color = cytokine_conc, group = cytokine_conc)) +
 #        xlim(0.1, 500) +
#          ylim(0, 1000) +      
#          scale_x_continuous(trans=scales::pseudo_log_trans(base = 2)) +
 #         scale_x_continuous(trans='log2') +
          geom_point() +
          stat_summary(fun = mean, geom = "point") +
          stat_summary(fun = mean, geom = "line") + 
          facet_grid(antibody_ID ~ Cell_Line)

ggplot(data=d1, aes(x=as.factor(cytokine_conc), y=Cell_W3 , color = drug_ID)) +
 #         xlim(0.1, 500) +
#          ylim(0, 1000) +      
#          scale_x_continuous(trans=scales::pseudo_log_trans(base = 2)) +
 #         scale_x_continuous(trans='log2') +
          geom_boxplot() +
          facet_grid(Cell_Line ~ Time_days)





```
```{r lapply antibodies}


# testing ground/template for antibody_plot function

     # data %>%
     # filter(antibody_ID=="PARP14") %>%
     # ggplot(aes(x=as.factor(cytokine_conc), y=Cell_W3 , color = drug_ID)) +
     # geom_boxplot() +
     # facet_grid(Cell_Line ~ Time_days) + 
     # labs(title=paste("Antibody:", "PARP14"))

# function that cycles through all antibodies in 'antibody' column
# uses filter to only select a single Ab
# plots the readout for a single readout (Cell_W3)
 
     antibody_plot <- function(filter, data) {

     data %>%
     filter(antibody_ID==filter) %>%
     ggplot(aes(x=as.factor(cytokine_conc), y=Cell_W3 , color = drug_ID)) +
          geom_boxplot() +
     facet_grid(Cell_Line ~ Time_days) +
     labs(title = paste("Antibody:", filter) ,
     caption = paste("Experiment ID:", Exp_ID))
     }             

ab <- unique(data$antibody_ID)
lapply(ab, antibody_plot, data)


```





```{r lapply readouts}

# Explore MAR antibody across all readouts

     # data %>%
     # filter(antibody_ID=="MAR") %>%
     # ggplot(aes(x=as.factor(cytokine_conc), y=Cell_W2 , color = drug_ID)) +
     # geom_boxplot() +
     # facet_grid(Cell_Line ~ Time_days) + 
     # labs(title=paste("Readout: cell_W2"))
     # 
     # 
     # 
     # data %>%
     # filter(antibody_ID=="MAR") %>%
     # ggplot(aes(x=as.factor(cytokine_conc), y=Cell_W3 , color = drug_ID)) +
     # geom_boxplot() +
     # facet_grid(Cell_Line ~ Time_days) + 
     # labs(title=paste("Readout: cell_W3"))
     # 
     # 
     # data %>%
     # filter(antibody_ID=="MAR") %>%
     # ggplot(aes(x=as.factor(cytokine_conc), y=Nuc_W2 , color = drug_ID)) +
     # geom_boxplot() +
     # facet_grid(Cell_Line ~ Time_days) + 
     # labs(title=paste("Readout: Nuc_W2"))
     # 
     # 
     # 
     # data %>%
     # filter(antibody_ID=="MAR") %>%
     # ggplot(aes(x=as.factor(cytokine_conc), y=Nuc_W3 , color = drug_ID)) +
     # geom_boxplot() +
     # facet_grid(Cell_Line ~ Time_days) + 
     # labs(title=paste("Readout: Nuc_W3")) 
     # 
     # 
     #      data %>%
     # filter(antibody_ID=="MAR") %>%
     # ggplot(aes(x=as.factor(cytokine_conc), y=Cyto_W2 , color = drug_ID)) +
     # geom_boxplot() +
     # facet_grid(Cell_Line ~ Time_days) + 
     # labs(title=paste("Readout: Cyto_W2"))
     # 
     # 
     # 
     # data %>%
     # filter(antibody_ID=="MAR") %>%
     # ggplot(aes(x=as.factor(cytokine_conc), y=Cyto_W3 , color = drug_ID)) +
     # geom_boxplot() +
     # facet_grid(Cell_Line ~ Time_days) + 
     # labs(title=paste("Readout: Cyto_W3")) 
   

# This lapply replaces the individual calls across all readouts for a single antibody
 
readout_plot <- function(readout, data) {  # print(paste("Readout:", readout, " and Antibody:", antibody)) }
 
     data %>%
     filter(antibody_ID=="MAR") %>%
     ggplot(aes_string(x="as.factor(cytokine_conc)", y=readout , color ="drug_ID")) +
     geom_boxplot() +
     facet_grid(Cell_Line ~ Time_days) +
     labs(title = paste("Readout:", readout, "\n Antibody: MAR"),
          caption = paste("Experiment ID:", Exp_ID))
     }

readouts <- c("Cell_W2", "Cell_W3", "Nuc_W2", "Nuc_W3", "Cyto_W2", "Cyto_W3", "Fraction_W2", "Fraction_W3", "Cell_No" )
myplots <- lapply(readouts, readout_plot, data)




```




```{r PDF of patch plot, fig.width=16, fig.height=12}
# fig.width=16, fig.height=12 in Mardown code stipulates the size of the images printed
# now combine the two approaches above and iterate through antibodies and readouts programmatically
# use mapply to cycle through two vectors


# function for two factor plot
two_factor_plot <- function(readout, antibody, data) {  # print(paste("Readout:", readout, " and Antibody:", antibody)) }
 
     data %>%
     filter(antibody_ID==antibody) %>%
     ggplot(aes_string(x="as.factor(cytokine_conc)", y=readout , color ="drug_ID")) +
     geom_boxplot() +
     facet_grid(Cell_Line ~ Time_days) +
     labs(title = paste("Readout:", readout, "\nAntibody:", antibody) ,
          caption = paste("Experiment ID:", Exp_ID))
     }


# generate pairwise combination of readouts and antibodies
readouts <- c("Cell_W2", "Cell_W3", "Nuc_W2", "Nuc_W3", "Cyto_W2", "Cyto_W3", "Fraction_W2", "Fraction_W3", "Cell_No" )
antibodies <- unique(data$antibody_ID)
combo <- expand.grid(readouts=readouts, antibodies=antibodies)

# call mapply with the combination

myplots <- mapply(two_factor_plot, as.character(combo[[1]]), as.character(combo[[2]]), MoreArgs = list(data), SIMPLIFY = FALSE)  



# using patchwork for layout

# single page with six plots
# arrange these functions based on the number and grouping per plot
# can arrange order here or with the 'combo' vector used to call the plotting function
six_patch_plot <- function(i, plots) {
         ( plots[[i]] + plots[[i+2]] + plots[[i+4]] ) / ( plots[[i+1]] + plots[[i+3]]  + plots[[i+5]] ) + plot_layout(guides = 'collect') }

three_patch_plot <- function(i, plots) {
         ( plots[[i+6]] + plots[[i+8]] + plot_spacer() ) / ( plots[[i+7]] + plot_spacer() + plot_spacer() ) + plot_layout(guides = 'collect') }

# plotting the groups of of 6 and 3 onto individual patchwork plots
composite1 <- lapply(c(1,10,19,28), six_patch_plot, myplots)
composite2 <- lapply(c(1,10,19,28), three_patch_plot, myplots)


# Stitching together the pdf file
# width and height needs match 'fig.width=16, fig.height=12' in Markdown code 

pdf(file = paste0(out_dir, out_file, ".pdf"),   # The directory you want to save the file in
    width = 16, # The width of the plot in inches
    height = 12) # The height of the plot in inches

for (i in 1:4) {
     print(composite1[[i]])
     print(composite2[[i]])
}
dev.off()
invisible(NULL)

```





